### ISSUE TITLE
Review and provide feedback

### ISSUE THREAD

**Issue by heratyian** [DPI-WE/rails-concerns#1]
@DPI-WE/teaching-assistants

**Comment by thierrychau** [comment]
Looks good. 

I'd add a quick mention that it's a common practice to name concerns "some_action"+"able" (e.g. "Csvable", "Taggable", etc.). Just so they know that the naming isn't following a strict Rails convention. Maybe at [line 51](https://github.com/DPI-WE/rails-concerns/blob/ef5770a5d35b419ca1a01a712a97ea40f906a2ab/content.md?plain=1#L51)?

**Comment by heratyian** [comment]
> I'd add a quick mention that it's a common practice to name concerns "some_action"+"able" (e.g. "Csvable", "Taggable", etc.). Just so they know that the naming isn't following a strict Rails convention. Maybe at [line 51](https://github.com/DPI-WE/rails-concerns/blob/ef5770a5d35b419ca1a01a712a97ea40f906a2ab/content.md?plain=1#L51)?

Done. Thanks for the reminder!
